apiVersion: v1
kind: Secret
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
stringData:
  {{- .Values.config.secretFiles | toYaml | nindent 2 }}
  