apiVersion: v1
kind: Secret
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
stringData:
  secrets.yaml: |-
    # Database url
    db_url: postgresql://{{ .Values.config.postgresql.username }}:{{ .Values.config.postgresql.password }}@{{ .Values.config.postgresql.hostname }}/{{ .Values.config.postgresql.database }}
    
    # Google Assistant configuration
    google_project_id: {{ .Values.config.google.projectId }}
  serviceAccount.json: {{ .Values.config.google.serviceAccount | quote }}
