apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "home-assistant.fullname" . }}
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "home-assistant.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "home-assistant.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
        - name: prepare-secrets
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          image: {{ include "home-assistant.image" . }}
          command:
          - sh
          - -c
          - envsubst < /tmp/secrets.yaml > /config/secrets.yaml
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: home-assistant.home-assistant-postgresql.credentials.postgresql.acid.zalan.do
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: home-assistant.home-assistant-postgresql.credentials.postgresql.acid.zalan.do
                  key: password
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
          volumeMounts:
            - name: secrets
              mountPath: /tmp/secrets.yaml
              subPath: secrets.yaml
            - name: config
              mountPath: /config
      containers:
        - name: home-assistant
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          image: {{ include "home-assistant.image" . }}
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
          volumeMounts:
            - name: secrets
              mountPath: /config/serviceAccount.json
              subPath: serviceAccount.json
            - name: config
              mountPath: /config
          resources:
            requests:
              memory: "512Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
      volumes:
        - name: secrets
          secret:
            secretName: {{ include "home-assistant.fullname" . }}
        - name: appconfig
          persistentVolumeClaim:
            claimName: {{ include "home-assistant.fullname" . }}
      securityContext:
        fsGroup: 1000
