apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "home-assistant.fullname" . }}
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "home-assistant.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "home-assistant.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
        - name: prepare-secrets
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          image: {{ include "home-assistant.image" . }}
          command:
          - sh
          - -c
          - |
            for secretFile in /secret-files/*; do
              envsubst < "$secretFile" > /secrets/$(basename "$secretFile")
            done
          env: {{- .Values.initEnv | toYaml | nindent 12 }}
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: secrets
              mountPath: /secrets
            # Secret files
            {{- range $k, $v := .Values.config.secretFiles }}
            - name: secret-files
              mountPath: /secret-files/{{ $k }}
              subPath: {{ $k }}
            {{- end }}
      containers:
        - name: home-assistant
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          image: {{ include "home-assistant.image" . }}
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
            # Secret files
            {{- range $k, $v := .Values.config.secretFiles }}
            - name: secrets
              mountPath: /config/{{ $k }}
              subPath: {{ $k }}
            {{- end }}
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "home-assistant.fullname" . }}
        - name: secret-files
          secret:
            secretName: {{ include "home-assistant.fullname" . }}
        - name: secrets
          emptyDir: {}
      securityContext:
        fsGroup: 1000
