global:
  containerRegistry: ghcr.io

image:
  registry: ""
  repository: jonaskop/home-assistant
  tag: ""

ingress:
  hostname: home-assistant.example.com
  annotations: {}

initEnv: {}

config:
  persistentFiles:
    .cloud: /config/.cloud
    .storage: /config/.storage
  configFiles:
    configuration.yaml: ""
  secretFiles:
    secrets.yaml: ""
